name: Continus integrations

on: [push]

jobs:
   continuos-integration:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v3
        - name: run install        
          uses: actions/setup-node@v2        
          with: 
            node-version: 18.
        - name: run install 
          run: |
            npm install   
            npm run build
            npx jest
        
            